// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRewardSystem {
  function rewardMint() external;

  function rewardListedCheck() external;
}
